### ISSUE TITLE
Bottom title is cropped

### ISSUE THREAD

**Issue by pinage404** [HadrienMP/mobtime#20]
Currently, the bottom title of the mob is cropped in the header, it's visible for letters with paw like "gpq"

Current

![image](https://user-images.githubusercontent.com/6325757/208091139-779042d6-898c-4af0-b153-a9acaff2f90c.png)

Fixed

![image](https://user-images.githubusercontent.com/6325757/208091099-883164ef-99de-4427-87dc-e9b0a6f98f9e.png)

**Comment by HadrienMP** [comment]
Fixed by increasing the line height, the overflow is to allow for ellipsis to work for long titles
