### ISSUE TITLE
What is the meaning of the icon at left of the icon profile ?

### ISSUE THREAD

**Issue by pinage404** [HadrienMP/mobtime#21]

**Comment by HadrienMP** [comment]
It's the socket connection status. It's probably not the best way to display it. Do you have any ideas how it could be better ?

**Comment by pinage404** [comment]
i have no idea at the moment

i don't see it anymore, where this information is displayed now ?

**Comment by HadrienMP** [comment]
I thought I explained the change here, but it must have split my mind.

I thought the icon was too cryptic, so I removed it. It will display the icon for disconnected only now. If you are disconnected from the server it will show a disconnected electric plug next to the user icon

**Comment by pinage404** [comment]
now, it's clear for me ! thanks

when i disconnected, i would like to have a bigger change in the interface

with the current behavior, it's just a small icon near an other one, i will miss it
