### ISSUE TITLE
Bug : can't rename a participant

### ISSUE THREAD

**Issue by pinage404** [HadrienMP/mobtime#8]
Steps to reproduce :

1. start a mob session
2. add a participant
3. try to rename the participant

Current behavior : when pressing key, the letter appear and disappear, the input is reset to the initial name

Expected behavior : we are able to rename a participant

**Comment by HadrienMP** [comment]
It's a bit complicated to do with the code right as it is right now to allow for edition. For now I made it clear that you can't edit it.
